const state={memory:[],quarantine:[],version:'—',protection:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
function table(records){if(!records.length)return '<div class="empty">No records available.</div>';return `<table><thead><tr><th>Status</th><th>Artifact</th><th>SHA-256</th></tr></thead><tbody>${records.slice(0,20).map(r=>`<tr><td><span class="badge ${r.restored_at?'cyan':'amber'}" style="color:var(--${r.restored_at?'cyan':'amber'})">${r.restored_at?'RESTORED':'ISOLATED'}</span></td><td title="${esc(r.original_path)}">${esc((r.original_path||'').split('/').pop())}</td><td><code>${esc((r.sha256||'').slice(0,18))}…</code></td></tr>`).join('')}</tbody></table>`}
function memoryTable(records){if(!records.length)return '<div class="empty">No validated immune-memory rules.</div>';return `<table><thead><tr><th>Rule</th><th>Trigger</th><th>Actions</th></tr></thead><tbody>${records.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc((r.trigger||[]).join(', '))}</td><td>${esc((r.actions||[]).join(', '))}</td></tr>`).join('')}</tbody></table>`}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const meta={overview:['System overview','A live local view of detection, containment and immune memory.'],detections:['Detection workspace','Run the same controlled scanner used by the CLI.'],memory:['Immune memory','Validated countermeasures retained by the system.'],quarantine:['Quarantine','Reversible containment and integrity state.'],telemetry:['Host telemetry','Read-only visibility into host security signals.']}[view];if(meta){$('title').textContent=meta[0];$('subtitle').textContent=meta[1]}history.replaceState(null,'',`#${view}`)}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return r.json()}
async function load(){try{const [health,memory,q]=await Promise.all([get('/api/health'),get('/api/memory'),get('/api/quarantine')]);state.version=health.version;state.protection=health.protection||{};state.memory=memory.entries||[];state.quarantine=q.records||[];$('version').textContent=state.version;$('footer-version').textContent=state.version;$('memory-count').textContent=state.memory.length;$('hero-memory').textContent=state.memory.length;$('quarantine-count').textContent=state.quarantine.length;$('quarantine-big').textContent=state.quarantine.length;const running=state.protection.running===true;$('protection-state').textContent=running?'PROTECTED':'CHECKING';$('protection-state').className=running?'green':'amber';$('protection-detail').textContent=running?`Event protection active · ${esc((state.protection.roots||[]).length)} watched location(s)`:'Protection service is not reporting as active';$('engine-state').textContent=running?'ACTIVE':'STANDBY';$('engine-dot').classList.toggle('offline',!running);$('activity').innerHTML=table(state.quarantine);$('memory-table').innerHTML=memoryTable(state.memory);$('quarantine-table').innerHTML=table(state.quarantine);$('updated').textContent=`updated ${new Date().toLocaleTimeString()}`}catch(e){$('updated').textContent='engine API unavailable';$('protection-state').textContent='OFFLINE';$('protection-state').className='amber';$('engine-state').textContent='OFFLINE';$('engine-dot').classList.add('offline')}}
async function runScan(){const target=$('target').value.trim();if(!target){$('scan-state').textContent='Enter a target path.';return}const btn=$('scan');btn.disabled=true;$('scan-state').textContent='Scanning…';$('results').innerHTML='<div class="empty">Analyzing evidence…</div>';try{const body=new URLSearchParams({target,deep:$('deep').checked?'1':'0',quarantine:$('do-quarantine').checked?'1':'0'});const response=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});if(!response.ok)throw new Error(`${response.status}`);const data=await response.json();if(!data.results?.length){$('results').innerHTML='<div class="empty">No suspicious findings.</div>'}else{$('results').innerHTML=`<table><thead><tr><th>Score</th><th>Confidence</th><th>Path</th><th>Signals</th><th>Action</th></tr></thead><tbody>${data.results.map(x=>`<tr><td>${esc(x.score)}</td><td>${esc(x.confidence)}</td><td>${esc(x.path)}</td><td>${esc((x.behaviors||[]).join(', '))}</td><td>${esc(x.message)}</td></tr>`).join('')}</tbody></table>`}$('scan-state').textContent=`Scan complete · ${data.results?.length||0} finding(s)`;await load()}catch(e){$('scan-state').textContent=`Scan failed: ${e.message}`;$('results').innerHTML='<div class="empty">The local engine rejected or could not process the request.</div>'}finally{btn.disabled=false}}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();show(b.dataset.jump)}));$('refresh').addEventListener('click',load);$('scan').addEventListener('click',runScan);$('target').addEventListener('keydown',e=>{if(e.key==='Enter')runScan()});
const initial=location.hash.slice(1);show(['overview','detections','memory','quarantine','telemetry'].includes(initial)?initial:'overview');load();setInterval(load,5000);
